### ISSUE TITLE
Setup testing frameworks

### ISSUE THREAD

**Issue by OliverDudgeon** [InformaticsMatters/mini-apps-data-tier-ui#13]
We should be end-to-end testing if we can. First we need to chose and setup the environment for the tests. I propose we use

- Cypress for end-to-end testing. This should be done first as it can cover the most ground.

These should be run as part of our CI with Github actions on commit. 

After this we can then write tests for the existing components and workflows.

NextJS now has [docs](https://nextjs.org/docs/testing) for setting this up.

**Comment by OliverDudgeon** [comment]
I have made a start here. I have cypress running a basic test and this runs inside a github action on every push.

Jobs that still need doing:

- [ ] - Integrate a login mechanism to test authenticated parts of the app
- [ ] - Integrate the code-coverage plugin of cypress and setup github badges with the results
- [ ] - Write tests for previous code @OliverDudgeon
- [ ] - Testing against an integration version of the API instead of staging @alanbchristie

**Comment by OliverDudgeon** [comment]
Package that might make this easier: https://github.com/sir-dunxalot/cypress-nextjs-auth0

**Comment by ag-m2ms** [comment]
Or possibly this (one)[https://github.com/Fredx87/cypress-keycloak-commands]. I managed to get a 401 response with it, which I assume is because of the fact that a new Cross-Origin with a different port (Cypress runs on a different one) for localhost is needed on the server's side.
If not I would need more information on how the auth is configured.

**Comment by OliverDudgeon** [comment]
Some progress has been made here on this branch [cypress-with-auth](https://github.com/InformaticsMatters/mini-apps-data-tier-ui/tree/cypress-with-auth)

**Comment by OliverDudgeon** [comment]
Resolved by switching to Playwright which handles multiple origins better
