### ISSUE TITLE
Replace DataTable component

### ISSUE THREAD

**Issue by OliverDudgeon** [InformaticsMatters/mini-apps-data-tier-ui#15]
The [Lisence](https://github.com/DevExpress/devextreme-reactive/blob/master/LICENSE.md) of the current table isn't friendly. We should either implement our own or find an alternative this needs:

- Custom columns
- Selection
- Search
- Filtering
- Sorting by column
- Resizable columns would be nice
- Some support for smaller screen sizes

We have chosen `react-table`.

Tasks:

- [x] Implement table
- [x] Implement selection
- [x] Implement search
- [ ] Implement filtering
- [x] Implement column sorting
- [ ] Implement a responsive layout
- [ ] Implement some form of pagination or virtualization

**Comment by tdudgeon** [comment]
Unimplemented tasks to be handled as new issues
