### ISSUE TITLE
Bulk actions on datasets

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#196]
Currently all actions have to be performed on an individual version of a dataset. This can be cumbersome.
We want to be able to select a number of entries and perform the action (e.g. delete) on all of them.

This will involve:

1. Allowing to 'expand' a row in the dataset table to show rows for each version (this is distinct from the expanded view of a dataset that should detail of just that dataset)
2. Adding a checkbox against each version to allow it to be selected
3. Providing bulk operation actions above the table to support Delete and Attach actions

**Comment by OliverDudgeon** [comment]
Expanded rows is possible based on this example https://react-table.tanstack.com/docs/examples/expanding

**Comment by OliverDudgeon** [comment]
How should the bulk requests be handled? The API doesn't support bulk actions currently. But the UI can make the actions in parallel and use `Promise.all` to `await` all of these. There's an example of this on the `tasks.tsx` page.

**Comment by tdudgeon** [comment]
When attaching multiple datasets the behaviour should be similar to that which is seen when uploading multiple datasets e.g. all are attached to the same place and the same options apply to files of the same type.

**Comment by tdudgeon** [comment]
As a follow on task we should allow to add labels to multiple items.
