### ISSUE TITLE
Project view enhancements

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#197]
These to some extent mirror the changes to the project display.

## File info
- File size property
- Created and last updated dates
See #195

## View/Edit data
See #195

## Bulk actions
See #196
Actions would be Delete, Detach

**Comment by OliverDudgeon** [comment]
Both size and modified times are not currently available in the UI.

**Comment by OliverDudgeon** [comment]
Size should be simple. Add a size column to the columns in the `ProjectTable` component and pass the data from the request into the `rows` array.

Display of times can use the `LocalTime` component or `toLocalTimeString` function which use the `dayjs` npm package.

**Comment by alanbchristie** [comment]
DM-API modifications taking place user story **sc-2537**

**Comment by alanbchristie** [comment]
Interestingly creation time is not something that *nix systems can generally offer.

> Files have a last-modified time (shown by "ls -l"), a last-accessed time (shown by "ls -lu") and an inode change time (shown by "ls -lc"). The latter is often referred to as the "creation time" - even in some man pages - but that's wrong; it's also set by such operations as mv, ln, chmod, chown and chgrp.

Having looked at the available frameworks and docs I'm not sure we can determine "creation time" for arbitrary (*unmanaged*) files. For *managed* files it's different - we have a DB which records the "publication time".
