### ISSUE TITLE
User settings page

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#198]
Exact details still need to be defined, but in brief:

1. Add a link to the user popup in the top right corner that takes you to a modal 'User Settings' page (a 'Messages' page will also follow in the future)
2. Add info and settings to that modal page. This will contain things like the users projects, usage stats etc. Exact details to follow.

**Comment by OliverDudgeon** [comment]
Should be possible to implement the modal with the general `ModalWrapper` component. See the `return` of the `FileUpload` component for an example.

**Comment by OliverDudgeon** [comment]
We don't have a generated client for the new api yet. This will take me some time which I don't really have at the moment. I suggest we just write react query hooks where needed for now.
