### ISSUE TITLE
Nothing displayed when job launching fails

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#300]
When launching a job fails (maybe because of a misconfiguration in the job) the server sends a 400 response, but the UI does nothing to suggest there is a problem. The job dialog stays open but there is no feedback.

**Comment by OliverDudgeon** [comment]
There is now a error toasts appearing

**Comment by OliverDudgeon** [comment]
This sufficient to close this or should more be done?
