### ISSUE TITLE
[Settings] Request failed with status code 404

### ISSUE THREAD

**Issue by NikolaStryckova** [InformaticsMatters/mini-apps-data-tier-ui#301]
#198 
 On the user settings page request failed with status code 503. 
Project stats were displayed after few minutes.
Errors in console - attachment
![2021-11-10_15h57_51](https://user-images.githubusercontent.com/92084528/141138103-bbe48b1d-7dcc-46aa-a556-41334afb5d9e.png)
.

**Comment by tdudgeon** [comment]
It might be that this happened while the backed was being redeployed, which happens quite often.
Check again in a few minutes and see if the error is still happening. For me it's working right now.

**Comment by NikolaStryckova** [comment]
Today request failed with status code 403.
I did a hard reset of the website (ctrl + F5), but the same situation.
Errors in console - attachment.
![2021-11-24_16h39_15](https://user-images.githubusercontent.com/92084528/143269157-ab4f5374-d618-47d5-8370-eeba3fb1edc3.png)
.
