### ISSUE TITLE
Open file info from task outputs

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#303]
The display of task info (on the tasks tab) includes a list of the output files for that job. These are displayed as hlinks that currently take you to the directory in the project Data tab that contains that file.

Now that we have the ability to display a file's contents we should instead open that page so the user can see the actual content of the output.

To run a job that generates such output:

1. Choose the "Playground" project
2. From the "Executions" tab run the "Select diverse subset of molecules" job.
3. Specify "chemspace-100000.smi" as the input, a name for the output file, and a number to pick. e.g.
![image](https://user-images.githubusercontent.com/647419/141141390-bf7a3132-5e82-43cc-8ad4-8b065d6bacc9.png)
4. Click run
5. Go to the "Tasks" tab and find the tasks for your job (it will be the top one)
6. Expand the tasks and look for the "Outputs" section: 
![image](https://user-images.githubusercontent.com/647419/141142389-cae9d618-747f-4daf-b0a6-4231c4e422d3.png)

In this case there will only be a single output, but other jobs will create multiple outputs.

Some outputs are defined using globs. e.g. "molecules/sha256/*/*/*.json".
Leave the behaviour unchanged for those for now.

**Comment by OliverDudgeon** [comment]
Each output file link should look like this:

🗀/file.ext

where the icon 🗀 links to the project page with directory set (like the current functionality) and the file name links to the page for the file.
