### ISSUE TITLE
[Project Stats] Numbers rounding

### ISSUE THREAD

**Issue by NikolaStryckova** [InformaticsMatters/mini-apps-data-tier-ui#308]
#198 On the Setting page is Project stats overview. Numbers of stats can be rounded. Picture in attachment with unrounded number of 'Available'.

![2021-11-10_16h10_15](https://user-images.githubusercontent.com/92084528/141266821-e4e58e54-a52f-4cb2-bcf4-eca266ba59fe.png)

**Comment by tdudgeon** [comment]
@alanbchristie Should this be done on the backed?

**Comment by ag-m2ms** [comment]
The 'Available' field is calculated on the FrontEnd. Should be easily fixed by wrapping it `Math.round` function.

**Comment by ag-m2ms** [comment]
The 'Available' field is calculated on the FrontEnd. Should be easily fixed by wrapping it in `Math.round` function.
