### ISSUE TITLE
[Data] Dropdown display issue 

### ISSUE THREAD

**Issue by NikolaStryckova** [InformaticsMatters/mini-apps-data-tier-ui#343]
**Description:** On the website Data is  dropdown display issue when adding a new project.
**Browser:** Google Chrome. 
**Note:** Video in attachment.

https://user-images.githubusercontent.com/92084528/143271927-ffd3d0bf-02da-4dbe-b9f6-90bb8c1cd4cb.mp4

.

**Comment by OliverDudgeon** [comment]
Project creation UI has changed now so this should be possible
