### ISSUE TITLE
[Data] Issue - adding a new project

### ISSUE THREAD

**Issue by NikolaStryckova** [InformaticsMatters/mini-apps-data-tier-ui#344]
**Description:** Unable create a new project. Errors displayed in the console. 
**Note:** Video in attachment, where you can also see console error.

https://user-images.githubusercontent.com/92084528/143275288-21307293-13ed-45db-b6dd-f42b7ca7fa91.mp4

s.

**Comment by OliverDudgeon** [comment]
Error message is now displayed in a toast message so hopefully we can track this down better if it's still possible.
