### ISSUE TITLE
[Projects] Filter task display

### ISSUE THREAD

**Issue by NikolaStryckova** [InformaticsMatters/mini-apps-data-tier-ui#345]
**Description:** _Enhancement_ - On the website Project we can filter tasks, but dropdown overlap filter field, so we can't see selected items. 
**Note:** Pictures in attachments
![2021-11-24_17h20_08](https://user-images.githubusercontent.com/92084528/143276467-3f4b653a-43a7-4ca3-9725-2172a5fef35b.png)
![2021-11-24_17h20_11](https://user-images.githubusercontent.com/92084528/143276479-3a345150-f57f-4795-8539-968b637ee1fc.png)
.

**Comment by OliverDudgeon** [comment]
This will be fixed with MUI 5 update #199
