### ISSUE TITLE
Links to inputs and outputs in sub-directories do not work

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#373]
For instance:
![image](https://user-images.githubusercontent.com/647419/145800328-1271ec64-d2e9-40fc-9106-3baa95b210ac.png)
The pull path is displayed in the title of the link, but the URL is missing the path.
e.g. https://squonk.informaticsmatters.org/data-manager-ui/project/project-e5223088-d682-48a0-929c-c641632adf22/file?file=dhfr-receptor-ph7.mol2

**Comment by OliverDudgeon** [comment]
Fixed with 32e30c82fceee1eeec3378f57d236a46f12c6976
