### ISSUE TITLE
Separate the datasets tab from the projects tab

### ISSUE THREAD

**Issue by OliverDudgeon** [InformaticsMatters/mini-apps-data-tier-ui#393]
We have decided that projects and the data table should be on different subroutes and accessed from different tabs. This will have the following result:

![image](https://user-images.githubusercontent.com/22367286/147235057-5b6333ea-0237-453b-a6c2-f01912527b74.png)

Of course this will need some work for this to look right on smaller screens.

**Comment by tdudgeon** [comment]
Data -> Datasets
