### ISSUE TITLE
C&P from plain text viewer is missing line feeds

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#410]
If you try to copy and paste the contents of the plain text viewer line feeds are missing from the pasted data.

**Comment by OliverDudgeon** [comment]
I can't reproduce this. When I copy a section into a plaintext editor, new lines are there. In fact an extra new line per line is pasted....

**Comment by OliverDudgeon** [comment]
Fixed with new viewer
