### ISSUE TITLE
Job selector UI should display items alphabetically

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#463]
It's quite hard to find files when selecting inputs for a job when the project has lots of files.

A simple fix would be to ensure that the files are listed in alphabetical order.

But in the medium term we should also allow user to apply filters.

**Comment by tdudgeon** [comment]
I wasn't using favourites. I don't think the problem will be so severe there, but those improvements would also be useful there.

**Comment by OliverDudgeon** [comment]
Will close this with the fix and create a new issue for the medium term changes
