### ISSUE TITLE
Add project owner to protect settings display

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#609]
We need to be able to see who owns each project in the settings view.
Add the owner as an additional column (after the project name).
I'm assuming this info is already available but if not we need an API enhancement.

**Comment by OliverDudgeon** [comment]
@tdudgeon I believe I only have the owner id of the org and unit. I would have to make a request to the DM-api for each product.

**Comment by tdudgeon** [comment]
@OliverDudgeon The info is present in the current response. e.g. 
```
{
  "projects": [
    {
      "editors": [
        "user1"
      ],
      "name": "Bezos",
      "organisation_id": "org-e9fe39f8-dbec-4992-b680-f16926a421f0",
      "owner": "user1",
      "private": false,
      "product_id": "product-d6d6fcfa-f472-482a-b788-0ac8f985d42a",
      "project_id": "project-6ef6fed5-fa3f-4353-9269-06facb64c0f4",
      "size": 111836293,
      "unit_id": "unit-b317fe55-608f-4d3a-b9c1-5edb19c4e243"
    }
...
```

In this case the `owner` is `user1` which is the user's username. We might want to add their full name to this response at some stage, but for now the username is enough.
