### ISSUE TITLE
Make the org, unit, project IDs accessible from the UI

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#642]
It would be useful to be able to C&P these ID from the UI.
Probably best to have a small section under each of these that list basic details of the selected item?
Could also contain other useful info such as creation date.

**Comment by OliverDudgeon** [comment]
Presumably Ids would only be displayed to admins?

**Comment by tdudgeon** [comment]
No, normal users might need this info too.
