### ISSUE TITLE
Allow to edit unit members

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#675]
If you are the owner of a unit then there should be a "Edit unit" option on the settings page that allows you to add or remove users from that unit.

**Comment by OliverDudgeon** [comment]
Doesn't seem possible with API currently?

**Comment by tdudgeon** [comment]
See:
https://squonk.it/account-server-api/api/#/user/app.api_user.unit_user_put
https://squonk.it/account-server-api/api/#/user/app.api_user.unit_user_delete
