### ISSUE TITLE
Ability to show debug events missing when showing single instance

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#677]
When a single instance is being displayed as a result of opening it after execution from the Executions tab, the toggle to show/hide debug level events is not present.

**Comment by OliverDudgeon** [comment]
Related to cleaning up instance responses from the API https://app.shortcut.com/informaticsmatters/story/3050/instance-response-tidy-up

**Comment by OliverDudgeon** [comment]
Fixed in 0c3ec1c4b7e3c2fc58da7cf39e7dc74c205ecb26
